location ^~ /v1/system/files {
  proxy_pass http://admin_backend;
  include /etc/nginx/proxy.conf;
}
location ^~ /v1/system/notifications {
  proxy_pass http://admin_backend;
  include /etc/nginx/proxy.conf;
}
location ^~ /v1/products {
  proxy_pass http://product_backend;
  include /etc/nginx/proxy.conf;
}
location ^~ /v1/orders {
  proxy_pass http://order_backend;
  include /etc/nginx/proxy.conf;
}
location / {
  proxy_pass http://admin_backend;
  include /etc/nginx/proxy.conf;
}
